DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS friends CASCADE;
DROP TABLE IF EXISTS mpa CASCADE;
DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS likes CASCADE;
DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS films_genres CASCADE;

CREATE TABLE IF NOT EXISTS users (
    userId BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    login VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    birthday DATE
);

CREATE TABLE IF NOT EXISTS friends (
   user1Id BIGINT REFERENCES users (userId),
   user2Id BIGINT REFERENCES users (userId),
   status_friend INT,
   FOREIGN KEY (user1Id) REFERENCES users (userId)
);

CREATE TABLE IF NOT EXISTS mpa (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
    filmId BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    releaseDate DATE,
    duration INT CHECK (duration > 0),
    mpa_id BIGINT,
    FOREIGN KEY (mpa_id) REFERENCES mpa(id)
);

CREATE TABLE IF NOT EXISTS genres (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS films_genres (
    filmId BIGINT,
    genre_id BIGINT NOT NULL,
    PRIMARY KEY (filmId, genre_id),
    FOREIGN KEY (filmId) REFERENCES films(filmId),
    FOREIGN KEY (genre_id) REFERENCES genres(id)
);

CREATE TABLE IF NOT EXISTS likes (
    filmId BIGINT NOT NULL,
    userId BIGINT NOT NULL,
    PRIMARY KEY (userId, filmId),
    FOREIGN KEY (filmId) REFERENCES films (filmId),
    FOREIGN KEY (userId) REFERENCES users (userId)
);